### ISSUE TITLE
NPE on openHAB start

### ISSUE THREAD

**Issue by BlackAlpha700** [pravussum/openhab2-addons#1]
On starting openHAB, an null pointer exception is thrown, but after this everything works fine and as expected.

`2018-11-19 11:44:12.485 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at org.openhab.binding.danfossairunit.internal.discovery.DanfossAirUnitDiscoveryService.discover(DanfossAirUnitDiscoveryService.java:70) ~[?:?]
        at org.openhab.binding.danfossairunit.internal.discovery.DanfossAirUnitDiscoveryService.lambda$0(DanfossAirUnitDiscoveryService.java:52) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
`

## Your Environment
* Version used: binding release from 18.11.2018
* Environment name and version: openHAB Testing, 2.4.0M5, OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
* Operating System and version: Ubunut 18.04.1 LTS, Kernel 4.15.0-39-generic

**Comment by pravussum** [comment]
I supposse you have additionally configured a thing in a config file which contains the host parameter?

**Comment by BlackAlpha700** [comment]
My danfossairunit.things look like this:

`danfossairunit:airunit:airunit [host="xxx.xxx.xxx.xxx", polling=1]`

**Comment by pravussum** [comment]
OK, that basically means that auto discovery is not working and it just works because you manually configured the IP address (same for me, btw). I'll have to look into it.
